Patryk/dev 5 add types to btn component
bright-bounty/quiz pull request #10
Opened 2022-09-19 16:29 UTC by Afanasi0101

2022-09-19 19:25 UTC, aleksanderwalczuk commented on quiz.code-workspace
> +      "path": "../Nowy folder"
remove it. How many times do I have to write it? Please don't waste my time.

2022-09-19 19:27 UTC, aleksanderwalczuk commented on src/components/btn.js
> +export default (createBtn);
remove parenthesis

2022-09-19 19:30 UTC, aleksanderwalczuk commented on src/scss/components/btn.scss
> +.btn_all{
set this name to `btn`

2022-09-19 19:31 UTC, aleksanderwalczuk commented on src/scss/components/btn.scss
> +.large_primary_btn{
`primary_btn_large` not `large_primary_btn`

2022-09-19 19:33 UTC, aleksanderwalczuk commented on src/components/btn.js
> +  baseLarge: 'btn_all large_base_btn',
adjust classes names according to previous comments

2022-09-19 19:39 UTC, aleksanderwalczuk commented on src/components/btn.js
>  }
We should check if provided `btnType` exists in our `btnTypes` object. If not then we should set the btnType as `base`.

2022-09-19 19:52 UTC, aleksanderwalczuk requested changes
This looks promising, but there are still some things we have to do:
- error prevention, check here https://github.com/bright-bounty/quiz/pull/10/files#r974607198
- we're missing the navigation button type
- there are few minor naming mistakes in css
- changes in workspace file should disappear ASAP

2022-09-20 12:07 UTC, aleksanderwalczuk commented on quiz.code-workspace
> +    },
...

2022-09-20 12:09 UTC, aleksanderwalczuk commented on src/components/btn.js
> +  navBtn: 'nav_btn',
it's all about buttons, so no need to add `Btn` to type name. Should be just `nav`

2022-09-20 12:09 UTC, aleksanderwalczuk commented on src/scss/components/btn.scss
> +.primary_btns{
this class name should be singular not plural

2022-09-20 12:11 UTC, aleksanderwalczuk commented on src/scss/components/btn.scss
> +.primary_btns{
we should keep it as following:
```css
.primary_btn {
  background-color: $color-red;
  color: $color-white;
  box-shadow: 0 0 15px $color-red;
  border: 1px solid $color-red;
  text-transform: uppercase;
  cursor: pointer;
  width: 600px;
}

2022-09-20 12:13 UTC, aleksanderwalczuk commented on src/scss/components/btn.scss
> +}
this should be removed. We can keep `width: 600px` and override `width` using `.primary_btn_large`

2022-09-20 12:30 UTC, Afanasi0101 commented on src/scss/components/btn.scss
> +.primary_btn:hover, .primary_btn_large:hover{
Why not ? it's a separate button

2022-09-22 13:52 UTC, aleksanderwalczuk approved these changes
🚀

2022-09-22 13:55 UTC, merged