added icon function
bright-bounty/quiz pull request #11
Opened 2022-09-24 09:41 UTC by Afanasi0101

2022-09-24 14:52 UTC, aleksanderwalczuk commented on index.html
> + <script type="module" src="/main.js"></script>
wrong indentation

2022-09-24 14:55 UTC, aleksanderwalczuk commented on src/components/btn.js
> +};
this is nice, but you put it in wrong place.

2022-09-24 14:55 UTC, aleksanderwalczuk commented on src/components/btn.js
> +
We should have a separate component for icon creation.

2022-09-24 15:00 UTC, aleksanderwalczuk commented on src/components/btn.js
> +  hatIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
we already know these are `icons` so we don't have to mention it in the key name.
Later on we'd have to pick it like so: `iconTypes[hatIcon]`. 
Wouldn't it be better to make it `iconTypes[hat]`? 
I think it's obviously better, what about you?

2022-09-24 15:01 UTC, aleksanderwalczuk commented on src/components/btn.js
> +  const typ = iconTypes[iconType];
what `typ` is?

2022-09-24 15:05 UTC, aleksanderwalczuk commented on src/scss/components/btn.scss
> +}
This is wrong, we should keep it in `icons.scss`

2022-09-24 15:07 UTC, aleksanderwalczuk requested changes
<img width="579" alt="Screenshot 2022-09-24 at 17 02 55" src="https://user-images.githubusercontent.com/33238158/192105047-79126be1-3b81-4dc4-912c-14215caf6993.png">

We have icons inside headers too, so we shouldn't add it to the button component.

Beside that, there is a file conflict in `btn` component because you forgot to git pull when you created new branch.

Please remove it make `git pull` on `dev` branch and start again. You can close this PR and make another one if you want to.

2022-09-25 13:21 UTC, Afanasi0101 commented on src/components/btn.js
> +  hatIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
I think you're right

2022-09-25 17:23 UTC, closed without merging