added folder with types
bright-bounty/quiz pull request #14
Opened 2022-10-04 14:18 UTC by Afanasi0101

2022-10-04 20:05 UTC, aleksanderwalczuk requested changes
Fix it quick and let's move on

2022-10-04 20:05 UTC, aleksanderwalczuk commented on src/components/contentWrapper.js
> +  const primaryBtn = createBtn('play the game', 'baseLargeBtn', primaryAction);
Then use the variable referring to that key in this function call.

2022-10-04 20:05 UTC, aleksanderwalczuk commented on src/components/icon.js
>  };
Same here.

2022-10-04 20:05 UTC, aleksanderwalczuk commented on src/types.js
> +`;
In this file we define only the keys. For type variable's please use the notation of uppercase combined with underscores as the example provided in the task description.

2022-10-06 16:49 UTC, Afanasi0101 commented
What u think about it ?

2022-10-06 17:08 UTC, aleksanderwalczuk requested changes
Looks better but there are still few changes to be made

2022-10-06 17:08 UTC, aleksanderwalczuk commented on src/components/btn.js
> +  NAV_BTN: 'nav',
Why only lg base btn is imported?

2022-10-06 17:08 UTC, aleksanderwalczuk commented on src/components/icon.js
> +  USER_ICON: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 user_icon">
You should add imports

2022-10-06 17:08 UTC, aleksanderwalczuk commented on src/types.js
> +export const NAV_BTN = 'nav';
I think nav isn't the best class name for a navigation button

2022-10-06 17:08 UTC, aleksanderwalczuk commented on src/types.js
> +`;
We should keep only key names in here.

2022-10-07 10:09 UTC, Afanasi0101 commented on src/types.js
> +`;
What do you mean ? 
1. export const HAT = `svg...` ;
2. export const HAT_ICON

2022-10-07 16:02 UTC, aleksanderwalczuk requested changes
Few more to go

2022-10-07 16:02 UTC, aleksanderwalczuk commented on src/types.js
> +`;
As values add `icon hat-icon` and following for the other one

2022-10-08 18:44 UTC, aleksanderwalczuk commented on src/components/contentWrapper.js
> +  const primaryBtn = createBtn('play the game', LARGE_BASE_BTN, primaryAction);
why `primaryBtn` has type of `LARGE_BASE_BTN`? 🤔

2022-10-08 18:44 UTC, aleksanderwalczuk commented on src/types.js
> +`;
https://github.com/bright-bounty/quiz/pull/14#discussion_r990245010

2022-10-08 18:45 UTC, aleksanderwalczuk commented on src/components/btn.js
> +  LARGE_BASE_BTN, PRIMARY_BTN, PRIMARY_BTN_LARGE, BASE_BTN, SMALL_BASE_BTN, NAV,
NAV isn't the best name for a button type ;)

2022-10-08 18:46 UTC, aleksanderwalczuk commented on src/types.js
> +`;
https://github.com/bright-bounty/quiz/pull/14#discussion_r990245010

2022-10-12 18:12 UTC, aleksanderwalczuk approved these changes
Lgtm

2022-10-13 09:46 UTC, merged