mrexwhoami2/dev-1-add-content-wrappers
bright-bounty/quiz pull request #5
Opened 2022-09-11 17:41 UTC by Afanasi0101

2022-09-11 21:17 UTC, aleksanderwalczuk requested changes

2022-09-11 21:17 UTC, aleksanderwalczuk commented on src/components/header.js
> +  header.classList.add('header-Wrapper');
this `-Wrapper` shouldn't be capitalised.

2022-09-11 21:17 UTC, aleksanderwalczuk commented on src/components/contentWrapper.js
> +  contentWrapper.dataset.view = 'main';
please remove the dataset, we won't use it for now.

2022-09-11 21:17 UTC, aleksanderwalczuk commented on src/components/contentWrapper.js
> +/* eslint-disable max-len */
you shouldn't disable the `max-len` rule. Remove this comment.

2022-09-11 21:17 UTC, aleksanderwalczuk commented on src/scss/components/index.scss
> +@import "./header.scss";
we don't need empty files. Please remove it.

2022-09-14 20:25 UTC, aleksanderwalczuk approved these changes
Please see final changes and merge when you do.

2022-09-14 20:25 UTC, aleksanderwalczuk commented on src/components/contentWrapper.js
> +  return contentWrapper;
@Afanasi0101 we should add the button to the contentWrapper like this.

2022-09-14 20:25 UTC, aleksanderwalczuk commented on src/app.js
> +  root.appendChild(contentBox);
So we can remove it from app ;)

2022-09-18 15:28 UTC, Afanasi0101 commented on src/app.js
> +  root.appendChild(contentBox);
why would we delete it?

2022-09-18 15:36 UTC, merged